// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "marchsoft@golang",
            "url": "http://marchsoft.cn/"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/code": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/01/26",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Authorization Controller"
                ],
                "summary": "获取图片验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseCode"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/01/26 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Authorization Controller"
                ],
                "summary": "登录授权接口",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        },
        "/api/file/uploadFile": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/01/27",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件：文件管理 File Controller"
                ],
                "summary": "文件上传（任意类型文件）",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseFile"
                        }
                    }
                }
            }
        },
        "/api/file/uploadImage": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/01/27",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件：文件管理 File Controller"
                ],
                "summary": "文件上传（图片）",
                "parameters": [
                    {
                        "type": "file",
                        "description": "file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseFile"
                        }
                    }
                }
            }
        },
        "/api/job": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/02/1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：岗位管理 job Controller"
                ],
                "summary": "查询岗位",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "current",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模糊查询",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序规则",
                        "name": "orders",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数据",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "创建时间",
                        "name": "startTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseGetJobList"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/02/1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：岗位管理 job Controller"
                ],
                "summary": "修改岗位",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateJob"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseInsertMenu"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/02/1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：岗位管理 job Controller"
                ],
                "summary": "新增岗位",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.AddJob"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseInsertMenu"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/02/1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：岗位管理 job Controller"
                ],
                "summary": "删除岗位",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseInsertMenu"
                        }
                    }
                }
            }
        },
        "/api/job/download": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：JiaKunLi 2021/02/1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：岗位管理 job Controller"
                ],
                "summary": "导出岗位数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "current",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "结束时间",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模糊查询",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序规则",
                        "name": "orders",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数据",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "创建时间",
                        "name": "startTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/api/menus": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Cgl 2021/01/30 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Menu Controller"
                ],
                "summary": "查询菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.SelectMenuDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseInsertMenu"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Cgl 2021/01/30 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Menu Controller"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteMenuDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseUpdateMenu"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Cgl 2021/01/30 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Menu Controller"
                ],
                "summary": "新增菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.InsertMenuDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseInsertMenu"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Cgl 2021/01/30 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Menu Controller"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteMenuDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseDeleteMenu"
                        }
                    }
                }
            }
        },
        "/api/menus/build": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Cgl 2021/02/01 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Menu Controller"
                ],
                "summary": "查询前端所需菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteMenuDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseSelectForeNeedMenu"
                        }
                    }
                }
            }
        },
        "/api/roles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "多条件查询角色",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "修改角色",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "新增角色",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        },
        "/api/roles/all": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "返回全部角色",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        },
        "/api/roles/download": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "导出角色数据",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        },
        "/api/roles/level": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "获取当前登录用户级别",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        },
        "/api/roles/menu": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "修改角色菜单",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        },
        "/api/roles/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Author：Ymq 2021/01/29 获得身份令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统：系统授权接口 Role Controller"
                ],
                "summary": "获取单个角色",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models._ResponseLogin"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bo.DeptCommon": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "bo.GetJobList": {
            "type": "object",
            "properties": {
                "enabled": {
                    "description": "状态：1启用（默认）、0禁用",
                    "type": "integer"
                },
                "job_sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string"
                }
            }
        },
        "bo.Job": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "bo.Order": {
            "type": "object",
            "properties": {
                "asc": {
                    "type": "string"
                },
                "column": {
                    "type": "string"
                }
            }
        },
        "bo.Role": {
            "type": "object",
            "properties": {
                "dataScope": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "bo.SelectForeNeedMenuBo": {
            "type": "object",
            "properties": {
                "alwaysShow": {
                    "type": "boolean"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bo.children"
                    }
                },
                "component": {
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "meta": {
                    "type": "object",
                    "$ref": "#/definitions/bo.meta"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                }
            }
        },
        "bo.UserInfoListBo": {
            "type": "object",
            "properties": {
                "count_id": {
                    "type": "integer"
                },
                "current": {
                    "type": "integer"
                },
                "hitCount": {
                    "type": "boolean"
                },
                "maxLimit": {
                    "type": "integer"
                },
                "optimizeCountSql": {
                    "type": "boolean"
                },
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bo.Order"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "records": {
                    "description": "记录查询",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bo.recordUser"
                    }
                },
                "searchCount": {
                    "type": "boolean"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "bo.children": {
            "type": "object",
            "properties": {
                "component": {
                    "type": "string"
                },
                "hidden": {
                    "type": "string"
                },
                "meta": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bo.meta"
                    }
                }
            }
        },
        "bo.meta": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "noCache": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "bo.recordUser": {
            "type": "object",
            "properties": {
                "avatarName": {
                    "type": "string"
                },
                "avatarPath": {
                    "type": "string"
                },
                "createBy": {
                    "type": "integer"
                },
                "createTime": {
                    "type": "integer"
                },
                "dept": {
                    "type": "object",
                    "$ref": "#/definitions/bo.DeptCommon"
                },
                "deptId": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "gender": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "jobs": {
                    "type": "object",
                    "$ref": "#/definitions/bo.Job"
                },
                "nickName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "pwdResetTime": {
                    "type": "integer"
                },
                "role": {
                    "type": "object",
                    "$ref": "#/definitions/bo.Role"
                },
                "updateTime": {
                    "type": "integer"
                },
                "updatedBy": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.AddJob": {
            "type": "object",
            "required": [
                "enabled",
                "jobSort",
                "name"
            ],
            "properties": {
                "enabled": {
                    "description": "岗位状态",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "jobSort": {
                    "description": "排序",
                    "type": "integer"
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string"
                }
            }
        },
        "dto.DeleteMenuDto": {
            "type": "object"
        },
        "dto.GetJobList": {
            "type": "object",
            "required": [
                "current",
                "orders",
                "size"
            ],
            "properties": {
                "current": {
                    "description": "当前页",
                    "type": "integer"
                },
                "endTime": {
                    "description": "结束时间",
                    "type": "integer"
                },
                "name": {
                    "description": "模糊查询",
                    "type": "string"
                },
                "orders": {
                    "description": "排序规则",
                    "type": "string"
                },
                "size": {
                    "description": "每页数据",
                    "type": "integer"
                },
                "startTime": {
                    "description": "创建时间",
                    "type": "integer"
                }
            }
        },
        "dto.InsertMenuDto": {
            "type": "object",
            "required": [
                "component",
                "icon",
                "id",
                "menuSort",
                "name",
                "path",
                "permission",
                "pid",
                "roles",
                "title",
                "type"
            ],
            "properties": {
                "cache": {
                    "type": "boolean"
                },
                "component": {
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "iframe": {
                    "type": "boolean"
                },
                "menuSort": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "dto.SelectMenuDto": {
            "type": "object",
            "required": [
                "current",
                "orders",
                "size"
            ],
            "properties": {
                "blurry": {
                    "type": "string"
                },
                "current": {
                    "type": "integer"
                },
                "endTime": {
                    "type": "integer"
                },
                "orders": {
                    "type": "string"
                },
                "pid": {
                    "description": "父id",
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "statTime": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateJob": {
            "type": "object",
            "required": [
                "enabled",
                "jobSort",
                "name"
            ],
            "properties": {
                "enabled": {
                    "description": "岗位状态",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "jobSort": {
                    "description": "排序",
                    "type": "integer"
                },
                "name": {
                    "description": "岗位名称",
                    "type": "string"
                }
            }
        },
        "dto.UserLoginDto": {
            "type": "object",
            "required": [
                "code",
                "password",
                "username",
                "uuid"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                },
                "uuid": {
                    "description": "验证码id",
                    "type": "string"
                }
            }
        },
        "models.FileResponse": {
            "type": "object",
            "properties": {
                "full_path": {
                    "description": "文件完整地址",
                    "type": "string"
                },
                "name": {
                    "description": "文件名",
                    "type": "string"
                },
                "path": {
                    "description": "文件相对地址",
                    "type": "string"
                },
                "size": {
                    "description": "文件大小",
                    "type": "integer"
                },
                "type": {
                    "description": "文件类型",
                    "type": "string"
                }
            }
        },
        "models._ResponseCode": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "img": {
                    "description": "base64验证码",
                    "type": "string"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                },
                "uuid": {
                    "description": "验证码id",
                    "type": "string"
                }
            }
        },
        "models._ResponseDeleteMenu": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseFile": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "$ref": "#/definitions/models.FileResponse"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseGetJobList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bo.GetJobList"
                    }
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseInsertMenu": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseInsertUser": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseLogin": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "properties": {
                        "token": {
                            "description": "授权令牌",
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseSelectForeNeedMenu": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "$ref": "#/definitions/bo.SelectForeNeedMenuBo"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseSelectUserInfoList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "$ref": "#/definitions/bo.UserInfoListBo"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "models._ResponseUpdateMenu": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务响应状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1.0",
	Host:        "127.0.0.1:8000",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "go-sword项目接口文档",
	Description: "基于gin的后台通用框架",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
